### ISSUE TITLE
MacOS install error

### ISSUE THREAD

**Issue by CyberSensei1** [namacha/python-magichue#11]
**Describe the bug**
Error on installing on MacOS

```python
--pip install python-magichue
Collecting python-magichue
  Using cached https://files.pythonhosted.org/packages/62/3c/d4d70ae822ee63b3682a329cb3e531235db483d93b3922c1e0f5b88c37a6/python-magichue-0.2.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/j5/6108wt4j24scty_gq4zqj1mc0000gn/T/pip-install-rI3olu/python-magichue/setup.py", line 3, in <module>
        import magichue
      File "magichue/__init__.py", line 1, in <module>
        from .magichue import Light
      File "magichue/magichue.py", line 6, in <module>
        import magichue.modes as modes
    ImportError: No module named modes
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/j5/6108wt4j24scty_gq4zqj1mc0000gn/T/pip-install-rI3olu/python-magichue/
```

**Device**
 - oobest wifibulb e27 6.5W

**Comment by namacha** [comment]
use python3
